# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a5f7006071601118e2aeca3e5598127f26053a5b520550d25b203ef6c20ee59a497bd4908d908464bcd901f97dcd86c5ec0b8cad81eb5e3601ab2b24fc88447

test:
  secret_key_base: ed6ad3b7677fdfebad69900059818aef1fff1515daf16bfb041d5d9c260a3f63793d65ad7eab27130e0015d0da36427fc7bce72990c6fdd966637d6d0654de74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
